server:
  port: 7200

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

elk:
  shutdown-after-load: false
  is-test-env: true
  skip-ws-connect: false
  elasticSearch:
    username: admin
    password: password123
    host: http://localhost:9200
  security:
    cors:
      allowed-hosts:
        - http://localhost:7200
        - http://localhost:7010
