version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=admin
      - ELASTIC_PASSWORD=password123
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      elk-net-dev:
        ipv4_address: 142.25.0.2

  kibana-dev:
    image: docker.elastic.co/kibana/kibana:8.3.3
    environment:
      - ELASTICSEARCH_USERNAME=admin
      - ELASTIC_PASSWORD=password123
    container_name: kibana-dev
    ports:
      - 5601:5601 
    depends_on:
      - elasticsearch
    networks:
      elk-net-dev:
        ipv4_address: 142.25.0.3


# aşağıdaki "name" parametresi değişirse build.gradle'da da değiştirilmeli. bkz. dbMigrate ve dbDrop
networks:
  elk-net-dev:
    name: elk-net-dev
    ipam:
      driver: default
      config:
        - subnet: 142.25.0.0/16
          gateway: 142.25.0.1